"""Generic OAuth2/OIDC provider framework (design doc §4.3 Azure Entra ID,
§4.4 Cognito/Google/GitHub, §10.3 OAuth2 security).

PKCE state and code_verifier are generated by the frontend, not this
module (design doc §7.1.6/§7.1.7) -- server/auth/oauth2_providers.py's
authorize/callback routes are a stateless relay: the server never stores
its own copy of the verifier between the two requests. `generate_pkce_pair`
below exists for tests and for any future server-driven flow.
"""

import base64
import hashlib
import secrets
from dataclasses import dataclass, field
from urllib.parse import urlencode

import httpx

from server.auth.oidc import IdTokenVerificationError, JwksUnavailableError, verify_id_token


class OAuth2Error(Exception):
    """Code exchange, token validation, or profile-fetch failure for any
    provider -- routes.py maps this to a generic 401/503 without leaking
    provider-internal error details to the client."""


class OAuth2ProviderUnavailableError(OAuth2Error):
    """The provider itself couldn't be reached (network/DNS/timeout failure
    talking to its token, JWKS, or profile endpoint) -- distinct from the
    provider actively rejecting the code/token, so routes.py can return a
    503 (transient, retry-worthy) instead of a 401 that wrongly implies the
    user's authorization code or credentials were the problem."""


@dataclass
class OAuth2ProviderSettings:
    name: str
    provider_type: str  # "azure", "google", "cognito", "github"
    client_id: str
    client_secret: str
    redirect_uri: str
    authorization_endpoint: str
    token_endpoint: str
    scopes: list[str] = field(default_factory=list)
    jwks_uri: str | None = None      # OIDC providers only (azure/google/cognito)
    issuer: str | None = None        # OIDC providers only
    label: str = ""
    # design doc §4.3 "allowed_groups": if non-empty, a login must present at
    # least one of these group identifiers (in the id_token's `groups`
    # claim) or be rejected -- OIDC providers only, checked in AuthService.
    allowed_groups: list[str] = field(default_factory=list)


def generate_pkce_pair() -> tuple[str, str]:
    """RFC 7636 S256: a high-entropy verifier and its SHA-256 challenge."""
    verifier = secrets.token_urlsafe(96)[:128]
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return verifier, challenge


def build_authorization_url(provider: OAuth2ProviderSettings, *, state: str, code_challenge: str) -> str:
    params = {
        "client_id": provider.client_id,
        "redirect_uri": provider.redirect_uri,
        "response_type": "code",
        "scope": " ".join(provider.scopes),
        "state": state,
        "code_challenge": code_challenge,
        "code_challenge_method": "S256",
    }
    return f"{provider.authorization_endpoint}?{urlencode(params)}"


async def _exchange_code_for_tokens(
    provider: OAuth2ProviderSettings, *, code: str, code_verifier: str, http_client: httpx.AsyncClient,
) -> dict:
    data = {
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": provider.redirect_uri,
        "client_id": provider.client_id,
        "client_secret": provider.client_secret,
        "code_verifier": code_verifier,
    }
    try:
        response = await http_client.post(
            provider.token_endpoint, data=data, headers={"Accept": "application/json"},
        )
    except httpx.HTTPError as exc:
        raise OAuth2ProviderUnavailableError(f"could not reach {provider.name} token endpoint: {exc}") from exc
    if response.status_code >= 400:
        raise OAuth2Error(f"{provider.name} token exchange failed ({response.status_code})")
    return response.json()


async def _fetch_github_profile(access_token: str, http_client: httpx.AsyncClient) -> dict:
    headers = {"Authorization": f"Bearer {access_token}", "Accept": "application/vnd.github+json"}
    try:
        user_resp = await http_client.get("https://api.github.com/user", headers=headers)
    except httpx.HTTPError as exc:
        raise OAuth2ProviderUnavailableError(f"could not reach GitHub: {exc}") from exc
    if user_resp.status_code >= 400:
        raise OAuth2Error(f"failed to fetch GitHub profile ({user_resp.status_code})")
    user = user_resp.json()

    email = user.get("email")
    if not email:
        try:
            emails_resp = await http_client.get("https://api.github.com/user/emails", headers=headers)
        except httpx.HTTPError as exc:
            raise OAuth2ProviderUnavailableError(f"could not reach GitHub: {exc}") from exc
        if emails_resp.status_code < 400:
            for entry in emails_resp.json():
                if entry.get("primary") and entry.get("verified"):
                    email = entry.get("email")
                    break

    return {
        "provider_user_id": str(user["id"]),
        "email": email,
        "email_verified": email is not None,
        "name": user.get("name") or user.get("login"),
        "picture": user.get("avatar_url"),
        "groups": [],
    }


async def resolve_provider_identity(
    provider: OAuth2ProviderSettings, *, code: str, code_verifier: str, http_client: httpx.AsyncClient,
) -> dict:
    """Exchanges `code` for tokens and returns a normalized identity dict:
    `provider_user_id`, `email`, `name`, `picture`. Raises OAuth2Error on
    any failure -- callers should treat that as an opaque auth failure."""
    tokens = await _exchange_code_for_tokens(provider, code=code, code_verifier=code_verifier, http_client=http_client)

    if provider.provider_type == "github":
        access_token = tokens.get("access_token")
        if not access_token:
            raise OAuth2Error("GitHub token exchange did not return an access_token")
        return await _fetch_github_profile(access_token, http_client)

    id_token = tokens.get("id_token")
    if not id_token:
        raise OAuth2Error(f"{provider.name} token exchange did not return an id_token")
    try:
        claims = await verify_id_token(
            id_token, jwks_uri=provider.jwks_uri, audience=provider.client_id, issuer=provider.issuer,
            http_client=http_client,
        )
    except JwksUnavailableError as exc:
        raise OAuth2ProviderUnavailableError(f"{provider.name} JWKS endpoint unreachable: {exc}") from exc
    except IdTokenVerificationError as exc:
        raise OAuth2Error(f"{provider.name} id_token verification failed: {exc}") from exc

    return {
        "provider_user_id": claims["sub"],
        "email": claims.get("email"),
        # Absent claim (common for enterprise IdPs like Azure Entra ID,
        # whose org-managed accounts don't always assert this) is treated
        # as "trust the provider", but an explicit False must block linking
        # (see AuthService.oauth2_login) -- some IdPs let a user register
        # with an email they don't yet control.
        "email_verified": claims.get("email_verified", True),
        "name": claims.get("name"),
        "picture": claims.get("picture"),
        "groups": claims.get("groups", []),
    }
